#!/usr/bin/env python3
"""
Patch mujoco_py so it reliably builds against and loads the GPU/EGL backend
instead of falling back to the CPU/OSMesa backend.

This fixes two independent bugs found the hard way on an HPC cluster with a
real GPU (H100) that free-mujoco-py==2.1.6 still couldn't use out of the box:

1. builder.py's get_nvidia_lib_dir() is supposed to detect a real GPU/driver
   and, if found, select LinuxGPUExtensionBuilder (EGL-based) instead of
   LinuxCPUExtensionBuilder (which needs system OSMesa dev headers,
   GL/osmesa.h, that most HPC clusters don't have installed — and installing
   them needs root). This detection is unreliable across mujoco_py releases:
   some gate it behind a flaky `type nvidia-smi` subprocess call, and
   free-mujoco-py==2.1.6 specifically never learned to check /usr/lib/nvidia
   at all (only /usr/local/nvidia/lib64 and /usr/lib/nvidia-XXX). This script
   replaces the whole function body with a strict superset check (all of the
   above paths, no subprocess gate).

2. Even with (1) fixed, mujoco_py/__init__.py unconditionally does
   `os.environ["LD_LIBRARY_PATH"] = <mujoco210/bin path>` at import time —
   a hard OVERWRITE, not an append. This silently wipes out whatever
   LD_LIBRARY_PATH your shell/job already had (including the GPU driver dir
   from fix 1), so builder.py's own later check for that path always fails
   with "Missing path to your environment variable" — even though you
   genuinely exported it beforehand. This script patches those assignments
   to prepend to the existing value instead of replacing it.

3. Even with (1) and (2) fixed, the bundled gl/eglplatform.h is an old
   (2015-era) Khronos header that unconditionally `#include <X11/Xlib.h>`
   for any __unix__ build — predating the MESA_EGL_NO_X11_HEADERS escape
   hatch later Khronos headers added for headless EGL. Most HPC clusters
   don't have X11 dev headers installed (and installing them needs root).
   mujoco_py's actual EGL usage (gl/eglshim.c) only ever calls
   eglGetPlatformDisplayEXT (the standard headless/device-based EGL path)
   and never touches a real Display/Window/Pixmap, so the X11 typedefs are
   dead weight here — this script replaces them with opaque `void*`/`int`
   stand-ins (the same trick newer upstream Khronos headers use for
   MESA_EGL_NO_X11_HEADERS builds) instead of requiring real X11 headers.

4. Even with (1)-(3) fixed, gl/eglshim.c does `#include <GL/glew.h>`, and
   free-mujoco-py==2.1.6's sdist is simply missing that header (a packaging
   bug — GLEW's headers are generated by its own build process and only
   ship in GLEW's release tarballs, not its git tree, so it's easy to drop
   when repackaging). The prebuilt libglewegl.so mujoco_py DOES bundle
   (mujoco_py/binaries/linux/mujoco210/bin/) is untouched by this — only the
   header used to compile against it is missing. This script copies a
   vendored GL/glew.h (../third_party/glew_header/, GLEW 2.1.0, BSD-style
   license) into mujoco_py's own vendor/egl/GL/ include directory (already
   on its build's include path) rather than requiring a system GLEW install.

5. Fix (2) (appending instead of overwriting LD_LIBRARY_PATH) exposes a
   second, independent bug: builder.py's fix_shared_library() calls
   (LinuxGPUExtensionBuilder._build_impl / LinuxCPUExtensionBuilder._build_impl)
   hardcode the patchelf --add-needed target as
   f'{os.environ["LD_LIBRARY_PATH"]}/{name}' — i.e. they assume
   LD_LIBRARY_PATH is a single directory containing every one of
   libmujoco210.so/libglewegl.so/libglewosmesa.so/libOpenGL.so.0/libEGL.so.1.
   That's only true in the original (unpatched) single-directory-overwrite
   behavior fix (2) had to remove — so once LD_LIBRARY_PATH is a real
   colon-separated PATH (as it must be for the OS's own dynamic linker),
   these calls embed the literal, nonexistent string
   "<entire LD_LIBRARY_PATH>/<name>" into the .so via patchelf, and it fails
   to dlopen at import time ("... cannot open shared object file"). This
   script replaces fix_shared_library() with a version that searches each
   directory in LD_LIBRARY_PATH for the real file and uses its actual
   resolved path (falling back to the bare library name — a normal system
   library lookup — for libraries like libOpenGL.so.0/libEGL.so.1 that live
   in standard system paths rather than anywhere on LD_LIBRARY_PATH).

You need to re-run this any time free-mujoco-py/mujoco_py gets reinstalled
(directly, or transitively via reinstalling robosuite/robomimic) — a fresh
install always overwrites these files with their original, unpatched source.
Safe to re-run any time; each fix is independently idempotent.

Usage:
    python scripts/patch_mujoco_py_gpu.py
"""
import ast
import glob
import importlib.util
import os
import re
import shutil
import sys

NEW_FUNC = '''def get_nvidia_lib_dir():
    # Patched by scripts/patch_mujoco_py_gpu.py (get_nvidia_lib_dir) — see its module docstring.
    docker_path = '/usr/local/nvidia/lib64'
    if exists(docker_path):
        return docker_path

    nvidia_path = '/usr/lib/nvidia'
    if exists(nvidia_path):
        return nvidia_path

    paths = sorted(glob.glob('/usr/lib/nvidia-[0-9][0-9][0-9]'))
    if paths:
        return paths[-1]

    return None
'''
BUILDER_MARKER = "# Patched by scripts/patch_mujoco_py_gpu.py (get_nvidia_lib_dir)"

# Matches the three (linux/darwin/win32) `os.environ["LD_LIBRARY_PATH"] = ...`
# overwrite lines in mujoco_py/__init__.py.
INIT_ASSIGN_RE = re.compile(r'^(\s*)os\.environ\["LD_LIBRARY_PATH"\] = (.+)$', re.MULTILINE)
INIT_MARKER = "# Patched by scripts/patch_mujoco_py_gpu.py"

# The exact X11 branch of gl/eglplatform.h's __unix__ case (verified against
# free-mujoco-py==2.1.6's bundled copy) and its no-X11 replacement.
EGL_X11_OLD = '''#elif defined(__unix__)

/* X11 (tentative)  */
#include <X11/Xlib.h>
#include <X11/Xutil.h>

typedef Display *EGLNativeDisplayType;
typedef Pixmap   EGLNativePixmapType;
typedef Window   EGLNativeWindowType;
'''
EGL_X11_NEW = '''#elif defined(__unix__)

/* Patched by scripts/patch_mujoco_py_gpu.py: stubbed out real X11 types —
   mujoco_py's eglshim.c only uses eglGetPlatformDisplayEXT (headless/
   device-based EGL), never a real X11 Display/Window/Pixmap. */
typedef void*    EGLNativeDisplayType;
typedef khronos_uintptr_t EGLNativePixmapType;
typedef khronos_uintptr_t EGLNativeWindowType;
'''
EGL_MARKER = "Patched by scripts/patch_mujoco_py_gpu.py"  # C file: no leading `#`

NEW_FIX_SHARED_LIBRARY = '''def fix_shared_library(so_file, name, library_path):
    # Patched by scripts/patch_mujoco_py_gpu.py (fix_shared_library) — see its module docstring.
    """ Used to fixup shared libraries on Linux """
    library_path = name
    for lib_dir in os.environ.get("LD_LIBRARY_PATH", "").split(os.pathsep):
        candidate = os.path.join(lib_dir, name)
        if lib_dir and os.path.exists(candidate):
            library_path = candidate
            break
    subprocess.check_call(['patchelf', '--remove-rpath', so_file])
    ldd_output = subprocess.check_output(['ldd', so_file]).decode('utf-8')

    if name in ldd_output:
        subprocess.check_call(['patchelf', '--remove-needed', name, so_file])
    subprocess.check_call(['patchelf', '--add-needed', library_path, so_file])
'''
FIX_SHARED_LIBRARY_MARKER = "# Patched by scripts/patch_mujoco_py_gpu.py (fix_shared_library)"


def find_package_dir():
    spec = importlib.util.find_spec("mujoco_py")
    if spec is None or not spec.submodule_search_locations:
        raise SystemExit("mujoco_py is not installed in this environment (pip install free-mujoco-py==2.1.6).")
    return list(spec.submodule_search_locations)[0]


def clear_build_cache(pkg_dir):
    generated_dir = os.path.join(pkg_dir, "generated")
    for stale in glob.glob(os.path.join(generated_dir, "_pyxbld_*")):
        shutil.rmtree(stale, ignore_errors=True)
        print(f"Cleared stale build cache: {stale}")


def patch_builder(pkg_dir):
    path = os.path.join(pkg_dir, "builder.py")
    src = open(path).read()

    if BUILDER_MARKER in src:
        print(f"{path} already patched, nothing to do.")
        return

    tree = ast.parse(src)
    target = next((n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == "get_nvidia_lib_dir"), None)
    if target is None:
        sys.exit(f"Could not find get_nvidia_lib_dir() in {path} — inspect it manually.")

    lines = src.splitlines(keepends=True)
    start, end = target.lineno - 1, target.end_lineno
    new_lines = lines[:start] + [NEW_FUNC] + lines[end:]
    open(path, "w").write("".join(new_lines))
    print(f"Patched {path}")


def patch_init(pkg_dir):
    path = os.path.join(pkg_dir, "__init__.py")
    src = open(path).read()

    if INIT_MARKER in src:
        print(f"{path} already patched, nothing to do.")
        return

    def repl(m):
        indent, expr = m.group(1), m.group(2)
        return (
            f'{indent}{INIT_MARKER}\n'
            f'{indent}os.environ["LD_LIBRARY_PATH"] = {expr} + os.pathsep + os.environ.get("LD_LIBRARY_PATH", "")'
        )

    new_src, n = INIT_ASSIGN_RE.subn(repl, src)
    if n == 0:
        sys.exit(f'Could not find `os.environ["LD_LIBRARY_PATH"] = ...` in {path} — inspect it manually.')
    open(path, "w").write(new_src)
    print(f"Patched {path} ({n} assignment(s) changed from overwrite to append)")


def patch_eglplatform(pkg_dir):
    path = os.path.join(pkg_dir, "gl", "eglplatform.h")
    if not os.path.exists(path):
        print(f"{path} not found — skipping (this mujoco_py build may not ship an EGL shim).")
        return
    src = open(path).read()

    if EGL_MARKER in src:
        print(f"{path} already patched, nothing to do.")
        return

    if EGL_X11_OLD not in src:
        sys.exit(
            f"{path} doesn't match the expected X11 block (different mujoco_py "
            "version?) — inspect its __unix__ branch manually."
        )
    open(path, "w").write(src.replace(EGL_X11_OLD, EGL_X11_NEW))
    print(f"Patched {path}")


def patch_fix_shared_library(pkg_dir):
    path = os.path.join(pkg_dir, "builder.py")
    src = open(path).read()

    if FIX_SHARED_LIBRARY_MARKER in src:
        print(f"{path} already patched (fix_shared_library), nothing to do.")
        return

    tree = ast.parse(src)
    target = next((n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name == "fix_shared_library"), None)
    if target is None:
        sys.exit(f"Could not find fix_shared_library() in {path} — inspect it manually.")

    lines = src.splitlines(keepends=True)
    start, end = target.lineno - 1, target.end_lineno
    new_lines = lines[:start] + [NEW_FIX_SHARED_LIBRARY] + lines[end:]
    open(path, "w").write("".join(new_lines))
    print(f"Patched {path} (fix_shared_library)")


def install_glew_header(pkg_dir):
    dest_dir = os.path.join(pkg_dir, "vendor", "egl", "GL")
    dest = os.path.join(dest_dir, "glew.h")
    if os.path.exists(dest):
        print(f"{dest} already present, nothing to do.")
        return

    src = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "third_party", "glew_header", "GL", "glew.h")
    if not os.path.exists(src):
        sys.exit(f"Vendored GLEW header not found at {src} — is third_party/glew_header/ present?")

    os.makedirs(dest_dir, exist_ok=True)
    shutil.copyfile(src, dest)
    print(f"Installed vendored GL/glew.h -> {dest}")


def main():
    pkg_dir = find_package_dir()
    patch_builder(pkg_dir)
    patch_fix_shared_library(pkg_dir)
    patch_init(pkg_dir)
    patch_eglplatform(pkg_dir)
    install_glew_header(pkg_dir)
    clear_build_cache(pkg_dir)


if __name__ == "__main__":
    main()
