dataset_type: "clevr"
dataset_name: null
dataset_config_name: null
train_data_dir: "cache_dir"
dataset_mode: "relative"
test_split_name: "validation"
image_key: "image"
class_key: "label"
num_classes: 1000

resolution: 256
center_crop: false
random_flip: false
vae_name: "stabilityai/sdxl-vae"
input_channels: 4