dataset_type: "hf"
dataset_name: "ILSVRC/imagenet-1k"
dataset_config_name: null
train_data_dir: null
test_split_name: "validation"
image_key: "image"
class_key: "label"
num_classes: 1000

resolution: 256
center_crop: true
random_flip: true
vae_name: "stabilityai/sdxl-vae"
input_channels: 4