dataset_type: "sokoban"
train_data_dir: "/net/tscratch/people/plgmgrzanka/diffusers/examples/trm_diffusion/sokoban/comparison/data/12-12-4"
eval_data_dir: "/net/tscratch/people/plgmgrzanka/diffusers/examples/trm_diffusion/sokoban/comparison/data/12-12-4-test"
resolution: 12
num_boxes: 4
input_channels: 3
k: 0
n_images_to_eval: 4
n_images_per_conditioning: 1
max_trajectories: null
max_training_boards: 100000
max_validation_boards: 20000
vae_name: null
center_crop: false
random_flip: false
concat_conditioning: false
