_target_: trm_models.UNetTRMv2
resolution: 12
n: 4
T: 2
n_sup: 4
core_model:
  _target_: diffusers.UNet2DModel
  sample_size: 12
  out_channels: 3
  in_channels: ${in_channels}
  num_class_embeds: ${num_class_embeds}
  block_out_channels: [64, 128]
  down_block_types:
    - "DownBlock2D"
    - "AttnDownBlock2D"
  up_block_types:
    - "AttnUpBlock2D"
    - "UpBlock2D"
  attention_head_dim: 64
  dropout: 0.1
  layers_per_block: 1
