# global_cond_dim = n_obs_steps * obs_dim = 2 * 20 = 40
_target_: models.action_backbones.ConditionalUnet1D
input_dim: ${data.action_dim}
global_cond_dim: 40
down_dims: [256, 512, 1024]
diffusion_step_embed_dim: 256
kernel_size: 5
n_groups: 8
cond_predict_scale: true
