seed: 0
compile: true

batch_size: 768
num_steps: 50000
gradient_accumulation_steps: 1
sudoku_loss_weight: 1.0
mse_loss_weight: 1.0
cfg_prob: 0.0

noisy_swap:
  prob: 0.0
  t_min: 80
  t_max: 100

classifier_loss:
  weight: 0.0
  t_max: 200
  target: "x0_pred"
  loss_type: "ce"
  noisy_classifier: false