_target_: models.UnifiedConditionDiT
condition_mode: "class"
num_classes: 100
sample_size: 32

in_channels: 12
out_channels: 8

num_layers: 2
patch_size: 2
attention_head_dim: 64 # 384 hidden / 6 heads
num_attention_heads: 6
cross_attention_dim: 1024
activation_fn: "gelu-approximate"