_target_: trm_models.RatatouilleDiTResidual
resolution: 32
downsample_factor: 2
n: 6
T: 3
n_sup: 4

core_model:
  _target_: models.UnifiedConditionDiT # Massive Painter
  condition_mode: "class_adaln"
  num_classes: 100
  sample_size: 32
  in_channels: 3
  out_channels: 3
  num_layers: 12
  patch_size: 2
  attention_head_dim: 64
  num_attention_heads: 6
  activation_fn: "gelu-approximate"

thinker_model:
  _target_: models.UnifiedConditionDiT # Tiny Thinker
  condition_mode: "class"
  num_classes: 100
  sample_size: 16
  in_channels: 64
  out_channels: 64
  num_layers: 2
  patch_size: 2
  attention_head_dim: 64
  num_attention_heads: 6
  cross_attention_dim: 1024
  activation_fn: "gelu-approximate"