_target_: trm_models.RatatouilleDiTResidual
resolution: 32
downsample_factor: 2
n: 6
T: 3
n_sup: 4

core_model:
  _target_: models.UnifiedConditionDiT # Massive Painter (Now fully blind!)
  condition_mode: "class_adaln" # Strips out cross-attention natively
  num_classes: 1000
  sample_size: 32
  in_channels: 4 # SDXL Latents
  out_channels: 4
  num_layers: 12
  patch_size: 2
  attention_head_dim: 64 # 768 hidden / 12 heads
  num_attention_heads: 12
  activation_fn: "gelu-approximate"

thinker_model:
  _target_: models.UnifiedConditionDiT # Tiny Thinker (Reads the sequence)
  condition_mode: "sequence"
  raw_dim: 55
  sample_size: 16
  in_channels: 128
  out_channels: 128
  num_layers: 2
  patch_size: 2
  attention_head_dim: 64
  num_attention_heads: 6
  cross_attention_dim: 512
  activation_fn: "gelu-approximate"