_target_: models.UnifiedConditionDiT
sample_size: 12
out_channels: 3
in_channels: ${in_channels}
# without condition mode

num_layers: 6
patch_size: 1
attention_head_dim: 64
num_attention_heads: 4
cross_attention_dim: 256 # 4 * 64 = 256
activation_fn: "gelu-approximate"
dropout: 0.1
