_target_: diffusers.UNet2DModel
sample_size: 12
in_channels: 3 # num_bits
out_channels: 3 # num_bits
block_out_channels: [224, 448, 672]
down_block_types:
  - "DownBlock2D"
  - "AttnDownBlock2D"
  - "AttnDownBlock2D"
up_block_types:
  - "AttnUpBlock2D"
  - "AttnUpBlock2D"
  - "UpBlock2D"
attention_head_dim: 64
dropout: 0.1
layers_per_block: 2
