_target_: trm_models.DiTTRMv2
resolution: 12
n: 6
T: 3
n_sup: 16

core_model:
  _target_: models_pt.UnifiedConditionDiT
  sample_size: 12
  out_channels: 3
  in_channels: ${in_channels}
  # without condition mode

  num_layers: 2
  patch_size: 1
  attention_head_dim: 64
  num_attention_heads: 3
  cross_attention_dim: 192

  activation_fn: "swiglu"
  dropout: 0.0
