_target_: trm_models.UNetTRMv2
state_channels: 3
resolution: 32
n: 6
T: 3
n_sup: 4
core_model:
  _target_: diffusers.UNet2DModel
  sample_size: 32
  in_channels: 3
  out_channels: 3
  layers_per_block: 1
  block_out_channels: [128, 128]
  down_block_types: ["AttnDownBlock2D", "DownBlock2D"]
  up_block_types: ["UpBlock2D", "AttnUpBlock2D"]
  num_class_embeds: 100