seq_len: 81
hidden_size: 512
n_heads: 8
L_layers: 2
L_cycles: 6
H_cycles: 3
n_sup: 16
expansion: 4.0
pos_encodings: "rope"
mlp_t: false

num_classes: 9
puzzle_emb_ndim: 512
puzzle_emb_len: 16
num_puzzle_identifiers: 1000
halt_exploration_prob: 0.0
freeze_weights: false

optim:
  lr: 1e-4
  lr_min_ratio: 1.0
  weight_decay: 1.0
  beta1: 0.9
  beta2: 0.95
  warmup_steps: 2000
  puzzle_emb:
    lr: 1e-4
    weight_decay: 1.0
    warmup_steps: ${thinker.optim.warmup_steps}
    lr_min_ratio: ${thinker.optim.lr_min_ratio}